### ISSUE TITLE
Add LNURL

### ISSUE THREAD

**Issue by reneaaron** [getAlby/alby-tools#1]
A common feature is to load information from a lightning address. 
This information is the lnurl-pay details and the keysend details.

Because not all ln addresses support CORS we optionally should request this information from an API endpoint (which is to be developed)

For the LNURL details we should add the functionality to request an invoice.

For the keysend details we should add the functionality to send a payment. 

some code usage ideas:

```js

const ln = new LightningAddress('satoshi@getalby.com');

console.log(ln.keysendDetails);
console.log(ln.lnurlPayDetails);

if (ln.hasKeysendDetails) {
  ln.pay({ amount: 100 } ); // does a webln.keysend() call with the correct details
}

if (ln.hasLnurlPay) {
  const invoice = await ln.requestInvoice({ amount: 100, comment: 'hello' });
}


```

**Comment by bumi** [comment]
@reneaaron is the current API good?

**Comment by reneaaron** [comment]
Looks good. 👌
