### ISSUE TITLE
Please consider using fetch instead of XMLHttpRequest

### ISSUE THREAD

**Issue by fishcakeday** [getAlby/alby-tools#29]
All modern browsers support fetch, and using XMLHttpRequest is no longer necessary. This will also make the tools compatible with the edge environments (e.g., Cloudflare Workers).

**Comment by bumi** [comment]
hmmm, we only use `fetch` where do you see `XMLHttpRequest`  being used? 

We use `cross-fetch` for node backwards compatibility. Is that maybe an issue? 🤔

**Comment by rolznz** [comment]
Fixed in https://github.com/getAlby/alby-tools/pull/32 

Thanks @fishcakeday !
